### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by codesForLiving** [rubensousa/BottomSheetBuilder#12]
android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:454)
android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:380)
android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:140)
android.app.Dialog.dismissDialog (Dialog.java:701)
android.app.Dialog.dismiss (Dialog.java:684)
com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog.access$101 (BottomSheetMenuDialog.java:34)
com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog$3.onStateChanged (BottomSheetMenuDialog.java:201)
android.support.design.widget.BottomSheetBehavior.setStateInternal (BottomSheetBehavior.java:576)
android.support.design.widget.BottomSheetBehavior$SettleRunnable.run (BottomSheetBehavior.java:757)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

Steps to reproduce :

1. Enable this option on your device: Settings -> Developer Options -> Don't keep Activities.

1. open bottomsheet, then click on any item which causes new activity to launch.

The old activity is removed, and causes the crash.

**Comment by rubensousa** [comment]
Thanks for the report. Will investigate as soon as I have more time.

**Comment by codesForLiving** [comment]
I think it is due to dismissing dialog after activity was destroyed. check for `isShowing` or surrounding `dismiss` with `try` `catch` will fix the issue. I am planning to use `BotthomSheetBuilder` in production, thanks for planning to look into it as soon as possible.

**Comment by rubensousa** [comment]
What was the exception thrown? Seems like the stacktrace isn't complete. I couldn't reproduce this even with the steps you said.

**Comment by codesForLiving** [comment]
It is the complete stacktrace, as recorded by firebaseCrash analytics. Also, googling for the stacktrace shows other people who have similar stack trace[not related to this lib].

I had 100% crash rate using the steps that I outlined.

There may be two cases I can think of 
 you remove the bottomsheet after click, in the app code.

or your phone removes the activity a bit late [low spec device] or the bottomsheet is removed before the activity is destroyed[high spec device]. Not very useful diagnosis.

**Comment by rubensousa** [comment]
Does it contain this somewhere?
```
java.lang.IllegalArgumentException: View not attached to window manager
```

**Comment by codesForLiving** [comment]
No

**Comment by rubensousa** [comment]
I'll probably just add the check for isShowing() like you requested, but I need to be able to reproduce it first.

**Comment by codesForLiving** [comment]
Tell me where, and I will make that change and test, if it fixes the issue. That way we can be sure it works.

**Comment by rubensousa** [comment]
https://github.com/rubensousa/BottomSheetBuilder/blob/master/bottomsheetbuilder/src/main/java/com/github/rubensousa/bottomsheetbuilder/BottomSheetMenuDialog.java#L199

```java
 if (newState == BottomSheetBehavior.STATE_HIDDEN && isShowing()) {

```

This should fix it

**Comment by codesForLiving** [comment]
Nope, it doesn't work.
Surrounding it with `try catch` solves the issue. I have verified.

http://stackoverflow.com/a/5102572/5455629

Also 

in the library

` mBehavior.setBottomSheetCallback(null);`

this is inside the block you suggested. I don't know if it will lead to memory leak or not if it is not called, when `isShowing` returns false. If yes, then the new check of `isshowing` and `try catch` should be there only for `.dimiss()` call

**Comment by rubensousa** [comment]
I would prefer to avoid the try catch approach here but I still couldn't reproduce the crash.
On what APIs are you reproducing this? I tested on 19, 22 and 25. 
I'm guessing this was fixed already in the standard Dialog class. 

Your stacktrace mentioned dismissDialog in Dialog.java:701

However that line doesn't match with the current class: https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/Dialog.java

**Comment by saipsa** [comment]
I am testing it on api 23. 

Also I am using 

```
compileSdkVersion 25
    buildToolsVersion '25.0.2'

Yes, I don't know why it mentions 701 line, my file has similar content as the file you have linked.
```
I retried, this time the stacktrace is from logcat of android studio

```
01-24 23:00:25.792 32245-32245/o.o.parser E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: o.o.parser, PID: 32245
                                                            java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{58a4d0a V.E...... R......D 0,0-720,1232} not attached to window manager
                                                                at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:454)
                                                                at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:380)
                                                                at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
                                                                at android.app.Dialog.dismissDialog(Dialog.java:701)
                                                                at android.app.Dialog.dismiss(Dialog.java:684)
                                                                at com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog.access$101(BottomSheetMenuDialog.java:34)
                                                                at com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog$3.onStateChanged(BottomSheetMenuDialog.java:201)
                                                                at android.support.design.widget.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:576)
                                                                at android.support.design.widget.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:757)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by codesForLiving** [comment]
I am testing it on api 23. 

Also I am using 

```
compileSdkVersion 25
    buildToolsVersion '25.0.2'

Yes, I don't know why it mentions 701 line, my file has similar content as the file you have linked.
```
I retried, this time the stacktrace is from logcat of android studio

```
01-24 23:00:25.792 32245-32245/o.o.parser E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: o.o.parser, PID: 32245
                                                            java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{58a4d0a V.E...... R......D 0,0-720,1232} not attached to window manager
                                                                at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:454)
                                                                at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:380)
                                                                at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
                                                                at android.app.Dialog.dismissDialog(Dialog.java:701)
                                                                at android.app.Dialog.dismiss(Dialog.java:684)
                                                                at com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog.access$101(BottomSheetMenuDialog.java:34)
                                                                at com.github.rubensousa.bottomsheetbuilder.BottomSheetMenuDialog$3.onStateChanged(BottomSheetMenuDialog.java:201)
                                                                at android.support.design.widget.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:576)
                                                                at android.support.design.widget.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:757)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by rubensousa** [comment]
I'll just go for the try catch solution. You can expect a release today.

**Comment by rubensousa** [comment]
1.5.1 released :)
